# Generated by Django 6.0.4 on 2026-04-29 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slogan', models.CharField(max_length=300, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('founded', models.IntegerField(verbose_name='Год основания')),
                ('logo_url', models.URLField(blank=True, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Корпорация',
                'verbose_name_plural': 'Корпорации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100, verbose_name='Псевдоним')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('rank', models.CharField(choices=[('script_kiddie', 'Script Kiddie'), ('netrunner', 'Netrunner'), ('elite', 'Elite Hacker'), ('ghost', 'Ghost')], default='netrunner', max_length=20, verbose_name='Ранг')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Аватар')),
                ('rep', models.IntegerField(default=0, verbose_name='Репутация')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackers', to='core.corporation', verbose_name='Корпорация')),
            ],
            options={
                'verbose_name': 'Хакер',
                'verbose_name_plural': 'Хакеры',
                'ordering': ['-rep'],
            },
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slot', models.CharField(choices=[('neural', 'Нейронный'), ('optical', 'Оптический'), ('physical', 'Физический'), ('software', 'Программный')], max_length=20, verbose_name='Слот')),
                ('price', models.IntegerField(verbose_name='Цена (кредиты)')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implants', to='core.corporation', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Имплант',
                'verbose_name_plural': 'Импланты',
                'ordering': ['slot', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reward', models.IntegerField(verbose_name='Награда (кредиты)')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Сложность')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('active', 'Активна'), ('completed', 'Завершена'), ('failed', 'Провалена')], default='open', max_length=20, verbose_name='Статус')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='core.corporation', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Миссия',
                'verbose_name_plural': 'Миссии',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.hacker', verbose_name='Хакер')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.mission', verbose_name='Миссия')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'unique_together': {('mission', 'hacker')},
            },
        ),
    ]
